/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <Wire.h>
#include <LiquidCrystalIO.h>
#include <IoAbstractionWire.h>
#include <RemoteConnector.h>
#include "SerialTransport.h"
#include <RemoteMenuItem.h>
#include <ScrollChoiceMenuItem.h>
#include <RuntimeMenuItem.h>
#include "tcMenuLiquidCrystal.h"

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;

// Global Menu Item exports
extern RemoteMenuItem menuConnectivityIoTMonitor;
extern BackMenuItem menuBackConnectivity;
extern SubMenuItem menuConnectivity;
extern ScrollChoiceMenuItem menuGridNewChoiceItem;
extern ActionMenuItem menuGridDown;
extern ActionMenuItem menuGridUp;
extern BooleanMenuItem menuGridLED2;
extern BooleanMenuItem menuGridLED1;
extern FloatMenuItem menuGridFloatValue;
extern BackMenuItem menuBackGrid;
extern SubMenuItem menuGrid;
extern Rgb32MenuItem menuRGB;
extern ListRuntimeMenuItem menuMyList;
extern BooleanMenuItem menuPeeled;
extern EnumMenuItem menuFoods;
extern AnalogMenuItem menuPercentage;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuPercentage; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

int fnMyListRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onGridDown(int id);
void CALLBACK_FUNCTION onGridLed1(int id);
void CALLBACK_FUNCTION onGridLed2(int id);
void CALLBACK_FUNCTION onGridUp(int id);

#endif // MENU_GENERATED_CODE_H
