/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "dynamicMenuItems_menu.h"
#include "ThemeCoolBlueTraditional.h"

// Global variable declarations
const  ConnectorLocalInfo applicationInfo = { "Dynamic Menus", "5f22995e-8da2-49c4-9ec8-d055901003af" };
IoAbstractionRef ioexp_io23017 = ioFrom23017(0x20, ACTIVE_LOW_OPEN, 10);
Adafruit_ST7735 gfx(1, 0, -1);
AdafruitDrawable gfxDrawable(&gfx);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);
MatrixKeyboardManager keyboard;
const char keyboardKeys[]  = "123A456B789C*0#D";
KeyboardLayout keyboardLayout(4, 4, keyboardKeys);
MenuEditingKeyListener tcMenuKeyListener('*', '#', 'A', 'B');

// Global Menu Item declarations
RENDERING_CALLBACK_NAME_INVOKE(fnIpItemRtCall, ipAddressRenderFn, "IpItem", -1, NO_CALLBACK)
IpAddressMenuItem menuIpItem(fnIpItemRtCall, 21, NULL);
RENDERING_CALLBACK_NAME_INVOKE(fnTextItemRtCall, textItemRenderFn, "TextItem", -1, NO_CALLBACK)
TextMenuItem menuTextItem(fnTextItemRtCall, 20, 5, &menuIpItem);
RENDERING_CALLBACK_NAME_INVOKE(fnRuntimesRtCall, backSubItemRenderFn, "Runtimes", -1, NO_CALLBACK)
const SubMenuInfo minfoRuntimes = { "Runtimes", 19, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackRuntimes(fnRuntimesRtCall, &menuTextItem);
SubMenuItem menuRuntimes(&minfoRuntimes, &menuBackRuntimes, NULL);
ListRuntimeMenuItem menuList(13, 0, fnListRtCall, &menuRuntimes);
const BooleanMenuInfo minfoDialogsBlockedBool = { "Blocked Bool", 18, 0xffff, 1, NO_CALLBACK, NAMING_TRUE_FALSE };
BooleanMenuItem menuDialogsBlockedBool(&minfoDialogsBlockedBool, false, NULL);
const AnyMenuInfo minfoDialogsBlockedAction = { "Blocked Action", 17, 0xffff, 0, NO_CALLBACK };
ActionMenuItem menuDialogsBlockedAction(&minfoDialogsBlockedAction, &menuDialogsBlockedBool);
RENDERING_CALLBACK_NAME_INVOKE(fnDialogsBlockedSubRtCall, backSubItemRenderFn, "Blocked Sub", -1, NO_CALLBACK)
const SubMenuInfo minfoDialogsBlockedSub = { "Blocked Sub", 15, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackDialogsBlockedSub(fnDialogsBlockedSubRtCall, NULL);
SubMenuItem menuDialogsBlockedSub(&minfoDialogsBlockedSub, &menuBackDialogsBlockedSub, &menuDialogsBlockedAction);
const BooleanMenuInfo minfoDialogsDialogBack = { "Allow Observer", 14, 0xffff, 1, onDialogBack, NAMING_ON_OFF };
BooleanMenuItem menuDialogsDialogBack(&minfoDialogsDialogBack, false, &menuDialogsBlockedSub);
const AnyMenuInfo minfoDialogsController = { "Controller", 12, 0xffff, 0, onDialogController };
ActionMenuItem menuDialogsController(&minfoDialogsController, &menuDialogsDialogBack);
const AnyMenuInfo minfoDialogsInformation = { "Information", 11, 0xffff, 0, onDialogInfo };
ActionMenuItem menuDialogsInformation(&minfoDialogsInformation, &menuDialogsController);
const AnyMenuInfo minfoDialogsQuestion = { "Question", 10, 0xffff, 0, onDialogQuestion };
ActionMenuItem menuDialogsQuestion(&minfoDialogsQuestion, &menuDialogsInformation);
RENDERING_CALLBACK_NAME_INVOKE(fnDialogsRtCall, backSubItemRenderFn, "Dialogs", -1, NO_CALLBACK)
const SubMenuInfo minfoDialogs = { "Dialogs", 9, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackDialogs(fnDialogsRtCall, &menuDialogsQuestion);
SubMenuItem menuDialogs(&minfoDialogs, &menuBackDialogs, &menuList);
const AnyMenuInfo minfoPizzaMakerStartCooking = { "Start Cooking", 8, 0xffff, 0, onStartCooking };
ActionMenuItem menuPizzaMakerStartCooking(&minfoPizzaMakerStartCooking, NULL);
extern char pizzaToppings[];
RENDERING_CALLBACK_NAME_INVOKE(fnPizzaMakerTopping3RtCall, enumItemRenderFn, "Topping 3", -1, NO_CALLBACK)
ScrollChoiceMenuItem menuPizzaMakerTopping3(7, fnPizzaMakerTopping3RtCall, 0, pizzaToppings, 10, 6, &menuPizzaMakerStartCooking);
extern char pizzaToppings[];
RENDERING_CALLBACK_NAME_INVOKE(fnPizzaMakerTopping2RtCall, enumItemRenderFn, "Topping 2", -1, NO_CALLBACK)
ScrollChoiceMenuItem menuPizzaMakerTopping2(6, fnPizzaMakerTopping2RtCall, 0, pizzaToppings, 10, 6, &menuPizzaMakerTopping3);
extern char pizzaToppings[];
RENDERING_CALLBACK_NAME_INVOKE(fnPizzaMakerTopping1RtCall, enumItemRenderFn, "Topping 1", -1, NO_CALLBACK)
ScrollChoiceMenuItem menuPizzaMakerTopping1(5, fnPizzaMakerTopping1RtCall, 0, pizzaToppings, 10, 6, &menuPizzaMakerTopping2);
const AnalogMenuInfo minfoPizzaMakerOvenTemp = { "Oven Temp", 4, 0xffff, 300, NO_CALLBACK, 0, 1, "C" };
AnalogMenuItem menuPizzaMakerOvenTemp(&minfoPizzaMakerOvenTemp, 0, &menuPizzaMakerTopping1);
RENDERING_CALLBACK_NAME_INVOKE(fnPizzaMakerRtCall, backSubItemRenderFn, "Pizza Maker", -1, NO_CALLBACK)
const SubMenuInfo minfoPizzaMaker = { "Pizza Maker", 3, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackPizzaMaker(fnPizzaMakerRtCall, &menuPizzaMakerOvenTemp);
SubMenuItem menuPizzaMaker(&minfoPizzaMaker, &menuBackPizzaMaker, &menuDialogs);
RENDERING_CALLBACK_NAME_INVOKE(fnOvenRtCall, backSubItemRenderFn, "Oven", -1, NO_CALLBACK)
const SubMenuInfo minfoOven = { "Oven", 2, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackOven(fnOvenRtCall, NULL);
SubMenuItem menuOven(&minfoOven, &menuBackOven, &menuPizzaMaker);
const BooleanMenuInfo minfoMainPower = { "Main Power", 1, 0xffff, 1, NO_CALLBACK, NAMING_ON_OFF };
BooleanMenuItem menuMainPower(&minfoMainPower, false, &menuOven);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).

    // Code generated by plugins.
    gfx.initR(INITR_BLACKTAB);
    gfx.setRotation(1);
    renderer.setUpdatesPerSecond(5);
    switches.init(internalDigitalIo(), SWITCHES_POLL_KEYS_ONLY, true);
    menuMgr.initForEncoder(&renderer, &menuMainPower, 6, 5, 9, FULL_CYCLE);
    keyboardLayout.setRowPin(0, 11);
    keyboardLayout.setRowPin(1, 10);
    keyboardLayout.setRowPin(2, 9);
    keyboardLayout.setRowPin(3, 8);
    keyboardLayout.setColPin(0, 15);
    keyboardLayout.setColPin(1, 14);
    keyboardLayout.setColPin(2, 13);
    keyboardLayout.setColPin(3, 12);
    keyboard.initialise(ioexp_io23017, &keyboardLayout, &tcMenuKeyListener, true);
    keyboard.setRepeatKeyMillis(850, 350);
    renderer.setTitleMode(BaseGraphicalRenderer::TITLE_FIRST_ROW);
    renderer.setUseSliderForAnalog(true);
    installCoolBlueTraditionalTheme(renderer, MenuFontDef(nullptr, 1), MenuFontDef(nullptr, 1), true);
}

