;FLAVOR:RepRap
;Generated with Cura_SteamEngine 3.6.0
;Degenerated by hand
T0
M106 S255 ;start with the fans on
M104 S200
M109 S200
M82 ;absolute extrusion mode
G21 ;metric values
G90 ;absolute positioning
M83 ;set extruder to relative mode
G92 E0 ;zero the extruded length
G1 F200 E10 ;extrude 10 mm of feed stock
G92 E0 ;zero the extruded length again
G1 F9000
;Put printing message on LCD screen
M117 Spooling...
;LAYER:1
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400
G1 F500 E400

M140 S0
M109 S20
M107
M104 S0 ;extruder heater off
G91 ;relative positioning

M84 ;steppers off
G90 ;absolute positioning
;Version _2.6 of the firmware can abort the print too early if the file ends
;too soon. However if the file hasn't ended yet because there are comments at
;the end of the file, it won't abort yet. Therefore we have to put at least 512
;bytes at the end of the g-code so that the file is not yet finished by the
;time that the motion planner gets flushed. With firmware version _3.3 this
;should be fixed, so this comment wouldn't be necessary any more. Now we have
;to pad this text to make precisely 512 bytes.
M83 ;relative extrusion mode
M104 S0
;End of Gcode
;SETTING_3 {"extruder_quality": ["[general]\\nversion = 4\\nname = Fine #2\\ndef
;SETTING_3 inition = ultimaker2\\n\\n[metadata]\\nposition = 0\\nquality_type = 
;SETTING_3 normal\\nsetting_version = 5\\ntype = quality_changes\\n\\n[values]\\
;SETTING_3 ncool_fan_speed = 60.0\\ndefault_material_print_temperature = 215\\ni
;SETTING_3 nfill_sparse_density = 100\\nwall_thickness = 1.2\\n\\n"], "global_qu
;SETTING_3 ality": "[general]\\nversion = 4\\nname = Fine #2\\ndefinition = ulti
;SETTING_3 maker2\\n\\n[metadata]\\nquality_type = normal\\nsetting_version = 5\
;SETTING_3 \ntype = quality_changes\\n\\n[values]\\nadhesion_type = skirt\\nsupp
;SETTING_3 ort_tree_enable = True\\nsupport_type = buildplate\\n\\n"}
